### ISSUE TITLE
Wykład 3 - Prof. dr hab. inż. Wielomianowicz

### ISSUE THREAD

**Issue by Kuborgc6** [daftcode/daftacademy-python_4beginners-autumn2020#10]
W zadaniu Wykład 3 - Prof. dr hab. inż. Wielomianowicz submit zwraca błąd, że klasa nie ma zaimplementowanej metody "from_iterable" mimo, że nie jest o to proszone w zadaniu. Czy zaliczone będzie zwrócenie zadania bez zaliczenia tego testu?

**Comment by wdebsqi** [comment]
Chyba chodzi o to, że kolejne zadania z wielomianów mają być budowane na poprzednich. Stąd założenie, że w tym zadaniu będziesz już mieć metodę _from_iterable_.
