### ISSUE TITLE
Trzecia praca domowa

### ISSUE THREAD

**Issue by ArtNowak** [daftcode/daftacademy-python_4beginners-autumn2020#2]
Czy trzecia praca domowa została już opublikowana? Z tego co zrozumiałem na wykładzie, miała się pojawić we wtorek. Nie widzę jej na repl.it i zastanawiam się, czy ze mną jest coś nie tak, czy po prostu jeszcze jej nie ma.

**Comment by naboru** [comment]
Tak, jest już opublikowana.
