### ISSUE TITLE
Wykład 3 - Dziel i rządź (praca domowa)

### ISSUE THREAD

**Issue by magladko** [daftcode/daftacademy-python_4beginners-autumn2020#3]
Dzień dobry,
mam problem z testami dla zadania "Dziel i rządź"
z jakiegoś powodu wywala mi testy:

- **increase_value_by_int** z kodem:
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 103, in test_increase_value_by_int
    self.assertIs(result, a)
AssertionError: MyFraction(numerator=2, denominator=1) is not MyFraction(numerator=1, denominator=1)
```
- **increase_value** z kodem:
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 141, in test_increase_value
    self.assertIs(result, a)
AssertionError: MyFraction(numerator=3, denominator=2) is not MyFraction(numerator=1, denominator=1)
```

Nie do końca rozumiem, co oznaczają te błędy, ponieważ gdy testuję ręcznie na różne sposoby dodawanie i zwiększanie ułamków zwracane są za każdym razem pożądane wartości.

Pozdrawiam,
Kornel Gładkowski

**Comment by Lekhi** [comment]
Potwierdzam. Również testowałem na różnych danych, które zwracają prawidłowy wynik, a nie przechodzę tych dwóch testów.

**Comment by BlueAlien99** [comment]
Dobra, trochę pokombinowałem i udało mi się zauważyć, że:
- `increase_value_by_int` oczekuje, że zwrócony zostanie zmodyfikowany obiekt
- `add_int_to_fraction` oczekuje, że zwrócony zostanie nowy obiekt

Niby ma sens, ale jak rozróżnić te dwie sytuacje? Bo odnoszę wrażenie, że one się wzajemnie wykluczają :/

**Comment by scp173astronau** [comment]
Główkując nad tym problemem pomyślałem, że te metody mają zmieniać licznik i mianownik obecnego obiektu oraz zwrócić jego kopię, jednak podczas testów dostałem taki błąd: 

> AssertionError: MyFraction(numerator=2, denominator=1) is not MyFraction(numerator=2, denominator=1)

Dalej nie wiem co robić

**Comment by BlueAlien99** [comment]
Ten błąd oznacza, że zwróciłeś kopię zamiast oryginalnego obiektu

**Comment by scp173astronau** [comment]
Jak próbuję zwrócić self czyli oryginalny obiekt to wywala:

> AssertionError: unexpectedly identical:

**Comment by BlueAlien99** [comment]
I właśnie na tym polega cały problem, który opisałem wyżej :)

**Comment by magladko** [comment]
dobra mnie już poszło, dzięki za wskazówki

z tego co zrozumiałem `__add__()` ma zwracać nowy obiekt
natomiast `__iadd__()` ma działać bezpośrednio na bieżącym obiekcie

**Comment by BlueAlien99** [comment]
Dzięki, @magladko! Nigdy nie pomyślałem, by zaimplementować `__iadd__()`, bo też nic nie było wspomniane o operatorze `+=` w instrukcji, ale mi też już się udało to rozwiązać :)
