### ISSUE TITLE
Wykład 3 - Prof. dr hab. inż. Wielomianowicz

### ISSUE THREAD

**Issue by jkiesiak** [daftcode/daftacademy-python_4beginners-autumn2020#4]
Cześć, 
Mam problem z klasą MyPolynomial, a mianowicie w zadaniu zaimplementowałam klasę, która działa i oraz zwraca to co powinna. Jednakże wspomniana klasa nie przechodzi testów, wyskakuje mi błąd:
Traceback (most recent call last):
_File "/home/runner/unit_tests.py", line 29, in test_degree
    assert MyPolynomial.from_iterable([0, 1, 0]).degree() == 1
_AttributeError:_ type object 'MyPolynomial' has no attribute 'from_iterable'_
Z tym że w zadaniu nie ma nic wspomniane o implementacji atrybutu from_iterable :D 
Czy mógłby mi ktoś doradzić co z tym? ;)

**Comment by BlueAlien99** [comment]
Wykonaj wcześniejsze zadanie, a dokładniej `Wykład 3 - Z listy powstałeś w wielomian się obrócisz` i wykonaj następne zadanie rozwijając kod klasy z poprzedniego :)
