### ISSUE TITLE
Implementacja Python

### ISSUE THREAD

**Issue by mateusz91t** [daftcode/daftacademy-python_4beginners-autumn2020#8]
Czy z powodu, że Python jest interpretowany, a nie kompilowany, może nie być najlepszym wyborem do pisania aplikacji typu enterprise?
Czy może być problemem ustalanie typów dopiero podczas użycia danego pakietu? Czy to jest problem i jeśli tak, to jak można go rozwiązać?
Czy ma to coś wspólnego z wersją CPython, o której wspomniał Pan Marcin na pierwszym wykładzie?

**Comment by naboru** [comment]
Co oznacza `aplikacji typu enterprise`? Jeśli to będzie webaplikacja to raczej nie ma przeciwskazań.

**Comment by mateusz91t** [comment]
@naboru, np. jakiś duży CRM. W dzisiejszym wykładzie Mateusz w sumie odpowiedział na to pytanie, Dzięki.
