### ISSUE TITLE
Z listy powstałeś w wielomian się obrócisz

### ISSUE THREAD

**Issue by koliber31** [daftcode/daftacademy-python_4beginners-autumn2020#9]
Hej,
chyba nie do końca rozumiem polecenie z zadania "Z listy powstałeś w wielomian się obrócisz". Mimo tego, że (jak mi się wydaje) metoda from_iterable zwraca to samo co __init__ wyskakuje mi assertion error. 
Kod:
class MyPolynomial:
  def __init__(self,*coefficients):
    self._coeff = list(coefficients)
  def from_iterable(self):
    return self

Błąd:
Traceback (most recent call last):
  File "python", line 8, in <module>
AssertionError

Natomiast 8 linijka to:
assert MyPolynomial.from_iterable([0, 1, 2]) == MyPolynomial(0, 1, 2)

**Comment by JWilczynski97** [comment]
Cześć. Przede wszystkim: Twoja metoda _from_iterable(self)_ **nie pobiera żadnych argumentów** i tu jest podstawowy błąd. Zauważ, że choćby w linijce z assert masz _from_iterable([0, 1, 2])_ podajemy listę [0,1,2] jako argument, a więc parametrem musi być jakiś obiekt typu iterable (lista, krotka). A w Twoim kodzie występuje tylko _self,_ które w zasadzie parametrem nie jest, a raczej informacją dla Pythona, że mamy do czynienia z metodą instancji klasy. 

I tutaj pojawia się kolejny problem, przyjrzyj się uważnie tej linijce:
assert MyPolynomial.from_iterable([0, 1, 2]) == MyPolynomial(0, 1, 2)

Wywołanie metody zapisem <nazwa_klasy>.<nazwa_metody> wskazuje na to, że my nie wywołujemy tej funkcji dla instancji klasy, a dla samej klasy. A więc będzie to class method, a nie metoda instancji. W związku z tym ciało funkcji również będzie wyglądało inaczej, bo nie może się w nim pojawić _self_. A więc metoda from_iterable do napisania jeszcze raz :)
Powodzenia!
